from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any


def write_review_html(ir: dict[str, Any], evidence: list[dict[str, Any]], analysis: dict[str, Any], destination: str | Path, max_measures: int = 8, engraved_pages: list[str] | None = None) -> Path:
    """Write a self-contained, dependency-free score/IR inspection page."""
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps({"ir": ir, "evidence": evidence, "analysis": analysis, "maxMeasures": max_measures}, ensure_ascii=False).replace("</", "<\\/")
    title = html.escape(ir["score"].get("title") or "Untitled")
    engraved = "".join(f'<section class="engraved-page">{page}</section>' for page in (engraved_pages or []))
    refs = {row["source_ref_id"]: row for row in ir["source_references"]}
    sounds = {note_id: sound["sounding_event_id"] for sound in ir["sounding_events"] for note_id in sound["source_note_ids"]}
    engraved_details = "".join(
        f'<section class="note-detail" id="detail-{event["note_id"]}"><h2>Note {html.escape(event["written_pitch"]["spelling"])}</h2>'
        f'<div class="card"><div class="k">Canonical ID</div><div class="v"><code>{event["note_id"]}</code></div></div>'
        f'<div class="card"><div class="k">원본 위치</div><div class="v">{html.escape(str(refs[event["source_ref_id"]].get("source_part_id")))} · m.{html.escape(str(refs[event["source_ref_id"]].get("source_measure_number")))} · element {refs[event["source_ref_id"]].get("source_element_index")}</div></div>'
        f'<div class="card"><div class="k">Global onset / duration</div><div class="v">{event["global_onset_quarter"]["numerator"]}/{event["global_onset_quarter"]["denominator"]} · {event["notated_duration_quarter"]["numerator"]}/{event["notated_duration_quarter"]["denominator"]}</div></div>'
        f'<div class="card"><div class="k">Tie / attack</div><div class="v">{event["tie_role"]} · {str(any(a["note_id"] == event["note_id"] for a in ir["attack_events"])).lower()}</div></div>'
        f'<div class="card"><div class="k">Sounding event</div><div class="v"><code>{sounds.get(event["note_id"], "–")}</code></div></div></section>'
        for event in ir["note_events"]
    )
    page = f"""<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} · MUSICANOTE IR Review</title>
<style>
:root{{--bg:#eef1f5;--panel:#fff;--ink:#17202a;--muted:#687180;--blue:#2563eb;--amber:#d97706;--line:#343a40}}
*{{box-sizing:border-box}} body{{margin:0;font:14px/1.45 system-ui,sans-serif;background:var(--bg);color:var(--ink)}}
header{{height:54px;background:#101820;color:white;display:flex;align-items:center;justify-content:space-between;padding:0 18px}}
.layout{{display:grid;grid-template-columns:minmax(650px,1fr) 360px;height:calc(100vh - 54px)}}
.left{{overflow:auto;padding:16px}} .paper{{background:#fffef8;min-height:700px;padding:18px;box-shadow:0 2px 8px #0002}}
.toolbar{{display:flex;gap:14px;align-items:center;margin-bottom:12px;flex-wrap:wrap}} label{{font-size:12px}}
#score{{width:100%;min-width:780px}} #engravedScore{{position:relative}} .engraved-page{{position:relative;margin:0 auto 18px;max-width:1100px;border-bottom:1px solid #ddd}} .engraved-page svg{{display:block;width:100%;height:auto}} .harmony-overlay{{position:absolute;z-index:8;transform:translateY(-100%);border:1px solid #d97706;border-radius:5px;background:#fff7d6e8;color:#713f12;padding:2px 6px;font:600 11px system-ui;cursor:pointer;box-shadow:0 1px 3px #0002;white-space:nowrap}} .harmony-overlay.low{{border-style:dashed;opacity:.82}} .harmony-overlay.selected{{background:#fde68a;outline:2px solid #f59e0b55}} .side{{background:var(--panel);border-left:1px solid #d8dce3;overflow:auto;padding:18px}}
.card{{border:1px solid #dde2e8;border-radius:8px;padding:12px;margin:10px 0}} .k{{font-size:10px;text-transform:uppercase;color:var(--muted);letter-spacing:.06em}} .v{{margin-top:3px;word-break:break-word}} .note-detail{{display:none}} .note-detail:target{{display:block}} .side:has(.note-detail:target)>#detailTitle,.side:has(.note-detail:target)>#detail{{display:none}}
.note{{cursor:pointer}} .note:hover ellipse,.note.sel ellipse{{fill:var(--blue)}} .engraved-page g.note[data-id^="note_"]{{cursor:pointer;pointer-events:all}} .engraved-page g.note[data-id^="note_"]:hover .notehead,.engraved-page g.note[data-id^="note_"].sel .notehead{{fill:var(--blue);color:var(--blue)}} .rest{{cursor:pointer}} .overlay{{cursor:pointer}}
.id-label{{font-size:8px;fill:#5f6b76}} .hidden{{display:none}} code{{font-size:11px}} .badge{{padding:3px 8px;border-radius:999px;background:#dcfce7;color:#166534;font-size:11px}}
@media(max-width:900px){{.layout{{grid-template-columns:1fr;height:auto}}.side{{border-left:0;border-top:1px solid #ddd}}}}
</style></head><body>
<header><strong>MUSICANOTE · Canonical IR Review</strong><span class="badge">Schema {ir['schema_version']}</span></header>
<div class="layout"><main class="left"><div class="paper">
<div class="toolbar"><strong>{title}</strong><button id="engravedMode" type="button">원본 조판 악보</button><button id="irMode" type="button">IR 검사 지도</button><label><input id="engravedHarmony" type="checkbox" checked> Harmony</label><span id="range"></span></div>
<div id="engravedScore">{engraved}</div>
<div id="irMap" class="hidden"><div class="toolbar"><label><input id="showIds" type="checkbox"> Canonical ID</label><label><input id="showSlices" type="checkbox" checked> Vertical slices</label><label><input id="showHarmony" type="checkbox" checked> Harmony hypotheses</label></div><svg id="score" role="img" aria-label="Canonical IR event map"></svg></div>
</div></main><aside class="side"><h2 id="detailTitle">곡 정보</h2><div id="detail"></div><div id="engravedDetails">{engraved_details}</div></aside></div>
<script id="payload" type="application/json">{payload}</script>
<script>
const D=JSON.parse(document.getElementById('payload').textContent),ir=D.ir,svg=document.getElementById('score'),NS='http://www.w3.org/2000/svg';
const rat=x=>x.numerator/x.denominator, E=(n,a={{}},t='')=>{{const x=document.createElementNS(NS,n);Object.entries(a).forEach(([k,v])=>x.setAttribute(k,v));x.textContent=t;return x}};
const measures=ir.measures.slice(0,D.maxMeasures), start=rat(measures[0].global_start_quarter), end=rat(measures.at(-1).global_start_quarter)+rat(measures.at(-1).nominal_duration_quarter);
const notes=ir.note_events.filter(n=>rat(n.global_onset_quarter)>=start&&rat(n.global_onset_quarter)<end), rests=ir.rest_events.filter(n=>rat(n.global_onset_quarter)>=start&&rat(n.global_onset_quarter)<end);
const staves=[...new Set([...notes,...rests].map(n=>n.display_staff_id))], W=1100, left=55, right=25, measureW=(W-left-right)/measures.length, staffH=105, H=70+staffH*staves.length;
svg.setAttribute('viewBox',`0 0 ${{W}} ${{H}}`); document.getElementById('range').textContent=`m.${{measures[0].printed_measure_number}}–m.${{measures.at(-1).printed_measure_number}} · ${{notes.length}} notes`;
const mx=t=>{{let i=measures.findIndex(m=>t>=rat(m.global_start_quarter)&&t<rat(m.global_start_quarter)+rat(m.nominal_duration_quarter));if(i<0)i=measures.length-1;const m=measures[i], rel=(t-rat(m.global_start_quarter))/rat(m.nominal_duration_quarter);return left+i*measureW+rel*measureW}};
function info(title, rows){{document.getElementById('detailTitle').textContent=title;document.getElementById('detail').innerHTML=rows.map(([k,v])=>`<div class="card"><div class="k">${{k}}</div><div class="v">${{v}}</div></div>`).join('')}}
function evidenceAt(onset){{return D.evidence.find(e=>e.type==='vertical_slice'&&rat(e.span.start)<=onset&&onset<rat(e.span.end))}}
function showHarmonySpan(h,button){{document.querySelectorAll('.harmony-overlay.selected').forEach(x=>x.classList.remove('selected'));button?.classList.add('selected');const alternatives=(h.alternatives||[]).length?(h.alternatives||[]).map(x=>`${{x.label}} (${{Math.round(x.confidence*100)}}%)`).join('<br>'):'기록된 대안 없음';info(`Harmony ${{h.selected.label}}`,[['Hypothesis ID',`<code>${{h.span_id}}</code>`],['Span',`${{h.range.start_offset_ql}}–${{h.range.end_offset_ql}} quarter · [start, end)`],['Selected',`${{h.selected.label}} · ${{Math.round(h.selected.confidence*100)}}%`],['Alternatives',alternatives],['Evidence',(h.selected.evidence||[]).map(e=>`${{e.code}}: ${{JSON.stringify(e.value)}}`).join('<br>')||'–'],['Status',`${{h.status}} · Analysis Layer`]])}}
function buildEngravedHarmony(){{document.querySelectorAll('.harmony-overlay').forEach(x=>x.remove());if(!document.getElementById('engravedHarmony').checked)return;const scoreBox=document.getElementById('engravedScore').getBoundingClientRect();(D.analysis.harmonic_spans||[]).forEach(h=>{{const start=Number(h.range.start_offset_ql),candidates=ir.note_events.filter(n=>rat(n.global_onset_quarter)>=start).sort((a,b)=>rat(a.global_onset_quarter)-rat(b.global_onset_quarter));const anchor=candidates.find(n=>document.querySelector(`.engraved-page g.note[data-id="${{n.note_id}}"]`));if(!anchor)return;const glyph=document.querySelector(`.engraved-page g.note[data-id="${{anchor.note_id}}"]`),box=glyph.getBoundingClientRect();if(!box.width&&!box.height)return;const button=document.createElement('button');button.type='button';button.className='harmony-overlay'+(h.selected.confidence<.6?' low':'');button.textContent=`${{h.selected.label}} ${{Math.round(h.selected.confidence*100)}}%`;button.style.left=`${{box.left-scoreBox.left}}px`;button.style.top=`${{box.top-scoreBox.top-5}}px`;button.title=`${{h.range.start_offset_ql}}–${{h.range.end_offset_ql}} quarter`;button.onclick=()=>showHarmonySpan(h,button);document.getElementById('engravedScore').append(button)}})}}
function draw(){{
 svg.replaceChildren(); staves.forEach((sid,si)=>{{const y=65+si*staffH;for(let l=0;l<5;l++)svg.append(E('line',{{x1:left,y1:y+l*9,x2:W-right,y2:y+l*9,stroke:'#343a40'}}));svg.append(E('text',{{x:4,y:y+20,'font-size':10,fill:'#687180'}},sid.slice(0,14)));for(let i=0;i<=measures.length;i++)svg.append(E('line',{{x1:left+i*measureW,y1:y,x2:left+i*measureW,y2:y+36,stroke:'#343a40'}}));}});
 measures.forEach((m,i)=>svg.append(E('text',{{x:left+i*measureW+5,y:48,'font-size':11,fill:'#687180'}},m.printed_measure_number)));
 const harmonyLayer=E('g',{{id:'harmonies'}});(D.analysis.harmonic_spans||[]).filter(h=>h.range.start_offset_ql<end&&h.range.end_offset_ql>start).forEach(h=>{{const x=mx(Math.max(start,h.range.start_offset_ql)),x2=mx(Math.min(end,h.range.end_offset_ql)),g=E('g',{{class:'overlay'}});g.append(E('rect',{{x,y:7,width:Math.max(22,x2-x),height:28,rx:5,fill:'#f59e0b22',stroke:'#d97706'}}));g.append(E('text',{{x:x+6,y:26,'font-size':12,fill:'#713f12'}},`${{h.selected.label}} ${{Math.round(h.selected.confidence*100)}}%`));g.onclick=()=>info(`Harmony ${{h.selected.label}}`,[['Hypothesis ID',`<code>${{h.span_id}}</code>`],['Range',`${{h.range.start_offset_ql}}–${{h.range.end_offset_ql}} quarter`],['Confidence',Math.round(h.selected.confidence*100)+'%'],['Evidence',(h.selected.evidence||[]).map(e=>`${{e.code}}: ${{JSON.stringify(e.value)}}`).join('<br>')],['Status','provisional analysis; Canonical Core 사실이 아닙니다.']]);harmonyLayer.append(g)}});svg.append(harmonyLayer);
 const sliceLayer=E('g',{{id:'slices'}});D.evidence.filter(e=>e.type==='vertical_slice').filter(e=>rat(e.span.start)<end&&rat(e.span.end)>start).forEach((e,i)=>{{const x=mx(Math.max(start,rat(e.span.start))),x2=mx(Math.min(end,rat(e.span.end)));const g=E('g',{{class:'overlay'}});g.append(E('rect',{{x,y:53,width:Math.max(2,x2-x),height:H-58,fill:i%2?'#2563eb0a':'#f59e0b0a'}}));g.onclick=()=>info('Vertical slice',[['Evidence ID',`<code>${{e.evidence_id}}</code>`],['Range',`${{rat(e.span.start)}}–${{rat(e.span.end)}} quarter`],['Pitch classes',e.pitch_classes.join(', ')||'rest'],['Lowest / highest',`${{e.bass_pitch??'–'}} / ${{e.top_pitch??'–'}}`],['Meaning','재계산 가능한 관찰 근거이며 화성 판정이 아닙니다.']]);sliceLayer.append(g)}});svg.prepend(sliceLayer);
 notes.forEach(n=>{{const si=staves.indexOf(n.display_staff_id),base=65+si*staffH+18,y=base-(n.written_pitch.midi_pitch-60)*3.4,x=mx(rat(n.global_onset_quarter));const g=E('g',{{class:'note'}});g.append(E('ellipse',{{cx:x,cy:y,rx:7,ry:5,fill:'#17202a',transform:`rotate(-18 ${{x}} ${{y}})`}}));g.append(E('line',{{x1:x+6,y1:y,x2:x+6,y2:y-27,stroke:'#17202a'}}));g.append(E('text',{{x:x-18,y:y+40,class:'id-label hidden'}},n.note_id.slice(-8)));g.onclick=()=>{{document.querySelectorAll('.note').forEach(x=>x.classList.remove('sel'));g.classList.add('sel');info(`Note ${{n.written_pitch.spelling}}`,[['Canonical ID',`<code>${{n.note_id}}</code>`],['Measure / onset',`${{n.measure_id}} · ${{rat(n.onset_in_measure)}}`],['Global quarter',rat(n.global_onset_quarter)],['Duration',rat(n.notated_duration_quarter)],['Voice / staff',`${{n.voice_id}}<br>${{n.display_staff_id}}`],['Tie / attack',`${{n.tie_role}} · ${{ir.attack_events.some(a=>a.note_id===n.note_id)}}`],['Source reference',`<code>${{n.source_ref_id}}</code>`]])}};svg.append(g)}});
 rests.forEach(r=>{{const si=staves.indexOf(r.display_staff_id),x=mx(rat(r.global_onset_quarter)),y=65+si*staffH+17;const g=E('g',{{class:'rest'}});g.append(E('rect',{{x:x-5,y:y-3,width:11,height:5,fill:'#17202a'}}));g.onclick=()=>info('Rest',[['Canonical ID',`<code>${{r.rest_id}}</code>`],['Global quarter',rat(r.global_onset_quarter)],['Duration',rat(r.notated_duration_quarter)]]);svg.append(g)}});
}}
document.getElementById('engravedMode').onclick=()=>{{document.getElementById('engravedScore').classList.remove('hidden');document.getElementById('irMap').classList.add('hidden')}};document.getElementById('irMode').onclick=()=>{{document.getElementById('engravedScore').classList.add('hidden');document.getElementById('irMap').classList.remove('hidden')}};
document.getElementById('showIds').onchange=e=>document.querySelectorAll('.id-label').forEach(x=>x.classList.toggle('hidden',!e.target.checked));document.getElementById('showSlices').onchange=e=>document.getElementById('slices').classList.toggle('hidden',!e.target.checked);document.getElementById('showHarmony').onchange=e=>document.getElementById('harmonies').classList.toggle('hidden',!e.target.checked);
function showEngravedNote(g){{const noteId=g.getAttribute('data-id'),n=ir.note_events.find(x=>x.note_id===noteId);if(!n)return;document.querySelectorAll('.engraved-page g.note.sel').forEach(x=>x.classList.remove('sel'));g.classList.add('sel');const ref=ir.source_references.find(x=>x.source_ref_id===n.source_ref_id),sound=ir.sounding_events.find(x=>x.source_note_ids.includes(n.note_id)),slice=evidenceAt(rat(n.global_onset_quarter));info(`Note ${{n.written_pitch.spelling}}`,[['Canonical ID',`<code>${{n.note_id}}</code>`],['원본 위치',`${{ref?.source_part_id??'–'}} · m.${{ref?.source_measure_number??'–'}} · element ${{ref?.source_element_index??'–'}}`],['Measure / onset',`${{n.measure_id}} · ${{rat(n.onset_in_measure)}}`],['Global quarter',rat(n.global_onset_quarter)],['Duration',rat(n.notated_duration_quarter)],['Voice / staff',`${{n.voice_id}}<br>${{n.display_staff_id}}`],['Tie / attack',`${{n.tie_role}} · ${{ir.attack_events.some(a=>a.note_id===n.note_id)}}`],['Sounding event',sound?`<code>${{sound.sounding_event_id}}</code>`:'–'],['Vertical slice',slice?`PC [${{slice.pitch_classes.join(', ')}}] · bass ${{slice.bass_pitch??'–'}} · top ${{slice.top_pitch??'–'}} · ${{slice.vertical_note_count}} sounding`:'–']])}}
window.mnShowNoteById=noteId=>{{const g=document.querySelector(`.engraved-page g.note[data-id="${{noteId}}"]`);if(g)showEngravedNote(g)}};
function bindEngravedNotes(){{document.querySelectorAll('.engraved-page g.note[data-id^="note_"]').forEach(g=>{{const handler=()=>showEngravedNote(g);g.onclick=handler;g.querySelectorAll('*').forEach(child=>child.onclick=handler)}})}}
bindEngravedNotes();window.addEventListener('DOMContentLoaded',()=>{{bindEngravedNotes();requestAnimationFrame(buildEngravedHarmony)}});window.addEventListener('resize',()=>requestAnimationFrame(buildEngravedHarmony));document.getElementById('engravedHarmony').onchange=buildEngravedHarmony;
draw();info('곡 정보',[['Score ID',`<code>${{ir.score.score_id}}</code>`],['Source',ir.source_files[0].original_name],['Engraving',`${{document.querySelectorAll('.engraved-page').length}} page(s), original MusicXML rendered by Verovio`],['Canonical links',`${{document.querySelectorAll('.engraved-page g.note[data-id^="note_"]').length}} engraved notes linked`],['IR map',`${{measures.length}} measures · ${{notes.length}} notes · ${{staves.length}} staves`],['안내','원본 조판 악보의 음표를 클릭하면 해당 Canonical event가 표시됩니다. IR 검사 지도에서는 시간축과 분석 근거를 별도로 확인할 수 있습니다.']]);
</script></body></html>"""
    destination.write_text(page, encoding="utf-8")
    return destination
